# Generated by Django 5.1 on 2025-12-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("partially_paid", "Partially Paid"),
                    ("paid", "Paid"),
                    ("overdue", "Overdue"),
                ],
                default="unpaid",
                max_length=20,
            ),
        ),
    ]
