# Generated by Django 5.1 on 2025-12-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_salesorder_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Primary email address",
                max_length=254,
                null=True,
                unique=True,
            ),
        ),
    ]
