from django.db import models
from django.core.validators import MinValueValidator
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.contrib.auth.models import User
from apps.purchase.models import PurchaseOrder, PurchaseOrderItem, SupplierPerformance
from apps.sales.models import SalesOrder, SalesOrderItem
from apps.inventory.models import Product, Category, Supplier


class ReportTemplate(models.Model):
    """Templates for generating reports."""
    REPORT_TYPE_CHOICES = [
        ('purchase_summary', _('Purchase Summary')),
        ('supplier_performance', _('Supplier Performance')),
        ('inventory_turnover', _('Inventory Turnover')),
        ('sales_vs_purchase', _('Sales vs Purchase Analysis')),
        ('financial_summary', _('Financial Summary')),
        ('custom', _('Custom Report')),
    ]

    name = models.CharField(_("Report Name"), max_length=100)
    report_type = models.CharField(_("Report Type"), max_length=30, choices=REPORT_TYPE_CHOICES)
    description = models.TextField(_("Description"), blank=True)

    # Report configuration
    date_range_required = models.BooleanField(_("Date Range Required"), default=True)
    supplier_filter = models.BooleanField(_("Supplier Filter"), default=False)
    product_filter = models.BooleanField(_("Product Filter"), default=False)
    category_filter = models.BooleanField(_("Category Filter"), default=False)

    # Template settings
    template_file = models.FileField(_("Template File"), upload_to='report_templates/', null=True, blank=True)
    default_parameters = models.JSONField(_("Default Parameters"), default=dict, blank=True)

    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='report_templates', verbose_name=_("Created By"))
    is_active = models.BooleanField(_("Active"), default=True)

    class Meta:
        verbose_name = _("Report Template")
        verbose_name_plural = _("Report Templates")
        ordering = ['name']

    def __str__(self):
        return self.name


class GeneratedReport(models.Model):
    """Generated report instances."""
    STATUS_CHOICES = [
        ('pending', _('Pending')),
        ('processing', _('Processing')),
        ('completed', _('Completed')),
        ('failed', _('Failed')),
    ]

    template = models.ForeignKey(ReportTemplate, on_delete=models.CASCADE, related_name='generated_reports', verbose_name=_("Report Template"))
    status = models.CharField(_("Status"), max_length=20, choices=STATUS_CHOICES, default='pending')

    # Report parameters
    parameters = models.JSONField(_("Parameters"), default=dict)
    start_date = models.DateField(_("Start Date"), null=True, blank=True)
    end_date = models.DateField(_("End Date"), null=True, blank=True)

    # Generated file
    report_file = models.FileField(_("Report File"), upload_to='generated_reports/', null=True, blank=True)
    file_format = models.CharField(_("File Format"), max_length=10, choices=[
        ('pdf', 'PDF'),
        ('excel', 'Excel'),
        ('csv', 'CSV'),
        ('html', 'HTML'),
    ], default='pdf')

    # Metadata
    generated_at = models.DateTimeField(_("Generated At"), null=True, blank=True)
    generated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='generated_reports', verbose_name=_("Generated By"))
    processing_time = models.DurationField(_("Processing Time"), null=True, blank=True)

    error_message = models.TextField(_("Error Message"), blank=True)
    is_active = models.BooleanField(_("Active"), default=True)

    class Meta:
        verbose_name = _("Generated Report")
        verbose_name_plural = _("Generated Reports")
        ordering = ['-generated_at']

    def __str__(self):
        return f"{self.template.name} - {self.generated_at or 'Pending'}"


class PurchaseReport(models.Model):
    """Purchase analytics and metrics."""
    report_date = models.DateField(_("Report Date"), default=timezone.now)
    period = models.CharField(_("Period"), max_length=20, choices=[
        ('daily', _('Daily')),
        ('weekly', _('Weekly')),
        ('monthly', _('Monthly')),
        ('quarterly', _('Quarterly')),
        ('yearly', _('Yearly')),
    ], default='monthly')

    # Purchase metrics
    total_orders = models.PositiveIntegerField(_("Total Orders"), default=0)
    total_order_value = models.DecimalField(_("Total Order Value"), max_digits=15, decimal_places=2, default=0)
    average_order_value = models.DecimalField(_("Average Order Value"), max_digits=12, decimal_places=2, default=0)

    # Supplier metrics
    total_suppliers = models.PositiveIntegerField(_("Total Suppliers"), default=0)
    active_suppliers = models.PositiveIntegerField(_("Active Suppliers"), default=0)

    # Product metrics
    total_products_purchased = models.PositiveIntegerField(_("Total Products Purchased"), default=0)
    top_product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True, related_name='top_purchase_reports', verbose_name=_("Top Product"))

    # Performance metrics
    on_time_delivery_rate = models.DecimalField(_("On-Time Delivery Rate (%)"), max_digits=5, decimal_places=2, default=0)
    order_accuracy_rate = models.DecimalField(_("Order Accuracy Rate (%)"), max_digits=5, decimal_places=2, default=0)

    # Financial metrics
    total_spent = models.DecimalField(_("Total Spent"), max_digits=15, decimal_places=2, default=0)
    average_cost_per_unit = models.DecimalField(_("Average Cost per Unit"), max_digits=10, decimal_places=2, default=0)

    class Meta:
        verbose_name = _("Purchase Report")
        verbose_name_plural = _("Purchase Reports")
        ordering = ['-report_date']
        unique_together = ['report_date', 'period']

    def __str__(self):
        return f"Purchase Report - {self.report_date} ({self.period})"


class SupplierPerformanceReport(models.Model):
    """Detailed supplier performance analytics."""
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE, related_name='performance_reports', verbose_name=_("Supplier"))
    report_date = models.DateField(_("Report Date"), default=timezone.now)
    period = models.CharField(_("Period"), max_length=20, choices=[
        ('monthly', _('Monthly')),
        ('quarterly', _('Quarterly')),
        ('yearly', _('Yearly')),
    ], default='monthly')

    # Order metrics
    total_orders = models.PositiveIntegerField(_("Total Orders"), default=0)
    completed_orders = models.PositiveIntegerField(_("Completed Orders"), default=0)
    cancelled_orders = models.PositiveIntegerField(_("Cancelled Orders"), default=0)

    # Delivery metrics
    on_time_deliveries = models.PositiveIntegerField(_("On-Time Deliveries"), default=0)
    late_deliveries = models.PositiveIntegerField(_("Late Deliveries"), default=0)
    average_delivery_days = models.DecimalField(_("Average Delivery Days"), max_digits=5, decimal_places=1, default=0)

    # Quality metrics
    quality_rating = models.DecimalField(_("Quality Rating"), max_digits=3, decimal_places=2, default=0)
    return_rate = models.DecimalField(_("Return Rate (%)"), max_digits=5, decimal_places=2, default=0)

    # Financial metrics
    total_order_value = models.DecimalField(_("Total Order Value"), max_digits=15, decimal_places=2, default=0)
    average_order_value = models.DecimalField(_("Average Order Value"), max_digits=12, decimal_places=2, default=0)
    payment_terms_compliance = models.DecimalField(_("Payment Terms Compliance (%)"), max_digits=5, decimal_places=2, default=0)

    class Meta:
        verbose_name = _("Supplier Performance Report")
        verbose_name_plural = _("Supplier Performance Reports")
        ordering = ['-report_date', 'supplier__name']
        unique_together = ['supplier', 'report_date', 'period']

    def __str__(self):
        return f"{self.supplier.name} Performance - {self.report_date}"

    @property
    def on_time_delivery_rate(self):
        """Calculate on-time delivery rate"""
        total_deliveries = self.on_time_deliveries + self.late_deliveries
        if total_deliveries > 0:
            return (self.on_time_deliveries / total_deliveries) * 100
        return 0

    @property
    def order_completion_rate(self):
        """Calculate order completion rate"""
        if self.total_orders > 0:
            return (self.completed_orders / self.total_orders) * 100
        return 0


class InventoryTurnoverReport(models.Model):
    """Inventory turnover and efficiency metrics."""
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='turnover_reports', verbose_name=_("Product"))
    report_date = models.DateField(_("Report Date"), default=timezone.now)
    period = models.CharField(_("Period"), max_length=20, choices=[
        ('monthly', _('Monthly')),
        ('quarterly', _('Quarterly')),
        ('yearly', _('Yearly')),
    ], default='monthly')

    # Inventory metrics
    beginning_inventory = models.PositiveIntegerField(_("Beginning Inventory"), default=0)
    ending_inventory = models.PositiveIntegerField(_("Ending Inventory"), default=0)
    average_inventory = models.DecimalField(_("Average Inventory"), max_digits=10, decimal_places=2, default=0)

    # Sales/Purchase metrics
    units_sold = models.PositiveIntegerField(_("Units Sold"), default=0)
    units_purchased = models.PositiveIntegerField(_("Units Purchased"), default=0)
    cost_of_goods_sold = models.DecimalField(_("Cost of Goods Sold"), max_digits=12, decimal_places=2, default=0)

    # Turnover calculations
    inventory_turnover_ratio = models.DecimalField(_("Inventory Turnover Ratio"), max_digits=5, decimal_places=2, default=0)
    days_inventory_outstanding = models.DecimalField(_("Days Inventory Outstanding"), max_digits=6, decimal_places=1, default=0)

    class Meta:
        verbose_name = _("Inventory Turnover Report")
        verbose_name_plural = _("Inventory Turnover Reports")
        ordering = ['-report_date', 'product__name']
        unique_together = ['product', 'report_date', 'period']

    def __str__(self):
        return f"{self.product.name} Turnover - {self.report_date}"

    def calculate_turnover(self):
        """Calculate inventory turnover metrics"""
        if self.average_inventory > 0:
            self.inventory_turnover_ratio = self.cost_of_goods_sold / self.average_inventory

        if self.inventory_turnover_ratio > 0:
            self.days_inventory_outstanding = 365 / self.inventory_turnover_ratio


class SalesVsPurchaseAnalysis(models.Model):
    """Analysis comparing sales and purchase performance."""
    report_date = models.DateField(_("Report Date"), default=timezone.now)
    period = models.CharField(_("Period"), max_length=20, choices=[
        ('monthly', _('Monthly')),
        ('quarterly', _('Quarterly')),
        ('yearly', _('Yearly')),
    ], default='monthly')

    # Sales metrics
    total_sales = models.DecimalField(_("Total Sales"), max_digits=15, decimal_places=2, default=0)
    sales_orders_count = models.PositiveIntegerField(_("Sales Orders Count"), default=0)
    average_sale_price = models.DecimalField(_("Average Sale Price"), max_digits=10, decimal_places=2, default=0)

    # Purchase metrics
    total_purchases = models.DecimalField(_("Total Purchases"), max_digits=15, decimal_places=2, default=0)
    purchase_orders_count = models.PositiveIntegerField(_("Purchase Orders Count"), default=0)
    average_purchase_price = models.DecimalField(_("Average Purchase Price"), max_digits=10, decimal_places=2, default=0)

    # Profitability metrics
    gross_margin = models.DecimalField(_("Gross Margin"), max_digits=12, decimal_places=2, default=0)
    gross_margin_percentage = models.DecimalField(_("Gross Margin (%)"), max_digits=5, decimal_places=2, default=0)

    # Product performance
    top_selling_product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True, related_name='top_sales_reports', verbose_name=_("Top Selling Product"))
    top_purchased_product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True, related_name='top_purchase_reports_analysis', verbose_name=_("Top Purchased Product"))

    class Meta:
        verbose_name = _("Sales vs Purchase Analysis")
        verbose_name_plural = _("Sales vs Purchase Analyses")
        ordering = ['-report_date']
        unique_together = ['report_date', 'period']

    def __str__(self):
        return f"Sales vs Purchase - {self.report_date} ({self.period})"

    def calculate_metrics(self):
        """Calculate profitability and performance metrics"""
        if self.total_sales > 0:
            self.gross_margin = self.total_sales - self.total_purchases
            self.gross_margin_percentage = (self.gross_margin / self.total_sales) * 100

        if self.sales_orders_count > 0:
            self.average_sale_price = self.total_sales / self.sales_orders_count

        if self.purchase_orders_count > 0:
            self.average_purchase_price = self.total_purchases / self.purchase_orders_count


class DashboardMetric(models.Model):
    """Real-time dashboard metrics."""
    METRIC_TYPE_CHOICES = [
        ('purchase_orders_today', _('Purchase Orders Today')),
        ('pending_deliveries', _('Pending Deliveries')),
        ('low_stock_alerts', _('Low Stock Alerts')),
        ('supplier_performance', _('Supplier Performance')),
        ('monthly_spending', _('Monthly Spending')),
        ('inventory_value', _('Inventory Value')),
        ('sales_revenue', _('Sales Revenue')),
        ('profit_margin', _('Profit Margin')),
    ]

    metric_type = models.CharField(_("Metric Type"), max_length=50, choices=METRIC_TYPE_CHOICES, unique=True)
    value = models.DecimalField(_("Value"), max_digits=15, decimal_places=2, default=0)
    unit = models.CharField(_("Unit"), max_length=20, blank=True, help_text=_("Unit of measurement (e.g., USD, %, count)"))
    last_updated = models.DateTimeField(_("Last Updated"), auto_now=True)

    # Additional data
    metadata = models.JSONField(_("Metadata"), default=dict, blank=True, help_text=_("Additional metric data"))

    class Meta:
        verbose_name = _("Dashboard Metric")
        verbose_name_plural = _("Dashboard Metrics")
        ordering = ['metric_type']

    def __str__(self):
        return f"{self.get_metric_type_display()} - {self.value} {self.unit}"
