# Generated by Django 5.1 on 2025-12-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_supplier_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock_quantity",
            field=models.IntegerField(default=0, verbose_name="Stock Quantity"),
        ),
    ]
