# Generated by Django 5.1 on 2025-12-14 18:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("inventory", "0002_initial"),
        ("purchase", "0002_initial"),
        ("sales", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Tax Name")),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("vat", "VAT"),
                            ("sales_tax", "Sales Tax"),
                            ("income_tax", "Income Tax"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Tax Type",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Rate (%)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "applicable_to_purchases",
                    models.BooleanField(
                        default=True, verbose_name="Applicable to Purchases"
                    ),
                ),
                (
                    "applicable_to_sales",
                    models.BooleanField(
                        default=True, verbose_name="Applicable to Sales"
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Effective Date"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="Expiry Date"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Tax Rate",
                "verbose_name_plural": "Tax Rates",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Account Number"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Account Name")),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("equity", "Equity"),
                            ("revenue", "Revenue"),
                            ("expense", "Expense"),
                        ],
                        max_length=20,
                        verbose_name="Account Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "parent_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_accounts",
                        to="account.account",
                        verbose_name="Parent Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
                "ordering": ["account_number"],
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Budget Name")),
                (
                    "budget_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual"),
                            ("quarterly", "Quarterly"),
                            ("monthly", "Monthly"),
                        ],
                        default="annual",
                        max_length=20,
                        verbose_name="Budget Type",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(default=2025, verbose_name="Year"),
                ),
                (
                    "quarter",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Q1"), (2, "Q2"), (3, "Q3"), (4, "Q4")],
                        null=True,
                        verbose_name="Quarter",
                    ),
                ),
                (
                    "month",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "01"),
                            (2, "02"),
                            (3, "03"),
                            (4, "04"),
                            (5, "05"),
                            (6, "06"),
                            (7, "07"),
                            (8, "08"),
                            (9, "09"),
                            (10, "10"),
                            (11, "11"),
                            (12, "12"),
                        ],
                        null=True,
                        verbose_name="Month",
                    ),
                ),
                (
                    "total_budget",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Total Budget",
                    ),
                ),
                (
                    "spent_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Spent Amount",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Budget category (e.g., Supplies, Equipment)",
                        max_length=100,
                        verbose_name="Category",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Department"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_budgets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget",
                "verbose_name_plural": "Budgets",
                "ordering": ["-year", "-month"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Payment Date"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("check", "Check"),
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("online_payment", "Online Payment"),
                        ],
                        max_length=20,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase Payment"),
                            ("sales", "Sales Receipt"),
                            ("expense", "Expense Payment"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Payment Type",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Reference Number"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Bank Name"
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Account Number"
                    ),
                ),
                (
                    "check_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Check Number"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "purchase_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="purchase.purchaseinvoice",
                        verbose_name="Purchase Invoice",
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="sales.salesorder",
                        verbose_name="Sales Order",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="inventory.supplier",
                        verbose_name="Supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Transaction Date",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")],
                        max_length=10,
                        verbose_name="Transaction Type",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="External reference number",
                        max_length=50,
                        verbose_name="Reference Number",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="account.account",
                        verbose_name="Account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "purchase_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="purchase.purchaseinvoice",
                        verbose_name="Purchase Invoice",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="purchase.purchaseorder",
                        verbose_name="Purchase Order",
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="sales.salesorder",
                        verbose_name="Sales Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-transaction_date", "-id"],
            },
        ),
    ]
