# Generated by Django 5.1 on 2025-12-14 18:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0002_initial"),
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("purchase_orders_today", "Purchase Orders Today"),
                            ("pending_deliveries", "Pending Deliveries"),
                            ("low_stock_alerts", "Low Stock Alerts"),
                            ("supplier_performance", "Supplier Performance"),
                            ("monthly_spending", "Monthly Spending"),
                            ("inventory_value", "Inventory Value"),
                            ("sales_revenue", "Sales Revenue"),
                            ("profit_margin", "Profit Margin"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Metric Type",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Value"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Unit of measurement (e.g., USD, %, count)",
                        max_length=20,
                        verbose_name="Unit",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metric data",
                        verbose_name="Metadata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Metric",
                "verbose_name_plural": "Dashboard Metrics",
                "ordering": ["metric_type"],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Report Name")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("purchase_summary", "Purchase Summary"),
                            ("supplier_performance", "Supplier Performance"),
                            ("inventory_turnover", "Inventory Turnover"),
                            ("sales_vs_purchase", "Sales vs Purchase Analysis"),
                            ("financial_summary", "Financial Summary"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=30,
                        verbose_name="Report Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "date_range_required",
                    models.BooleanField(
                        default=True, verbose_name="Date Range Required"
                    ),
                ),
                (
                    "supplier_filter",
                    models.BooleanField(default=False, verbose_name="Supplier Filter"),
                ),
                (
                    "product_filter",
                    models.BooleanField(default=False, verbose_name="Product Filter"),
                ),
                (
                    "category_filter",
                    models.BooleanField(default=False, verbose_name="Category Filter"),
                ),
                (
                    "template_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="report_templates/",
                        verbose_name="Template File",
                    ),
                ),
                (
                    "default_parameters",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Default Parameters"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Template",
                "verbose_name_plural": "Report Templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(default=dict, verbose_name="Parameters"),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Start Date"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "report_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="generated_reports/",
                        verbose_name="Report File",
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("html", "HTML"),
                        ],
                        default="pdf",
                        max_length=10,
                        verbose_name="File Format",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Generated At"
                    ),
                ),
                (
                    "processing_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Processing Time"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error Message"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Generated By",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to="reports.reporttemplate",
                        verbose_name="Report Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated Report",
                "verbose_name_plural": "Generated Reports",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryTurnoverReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Report Date"
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="Period",
                    ),
                ),
                (
                    "beginning_inventory",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Beginning Inventory"
                    ),
                ),
                (
                    "ending_inventory",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ending Inventory"
                    ),
                ),
                (
                    "average_inventory",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Average Inventory",
                    ),
                ),
                (
                    "units_sold",
                    models.PositiveIntegerField(default=0, verbose_name="Units Sold"),
                ),
                (
                    "units_purchased",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Units Purchased"
                    ),
                ),
                (
                    "cost_of_goods_sold",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Cost of Goods Sold",
                    ),
                ),
                (
                    "inventory_turnover_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Inventory Turnover Ratio",
                    ),
                ),
                (
                    "days_inventory_outstanding",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=6,
                        verbose_name="Days Inventory Outstanding",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turnover_reports",
                        to="inventory.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Turnover Report",
                "verbose_name_plural": "Inventory Turnover Reports",
                "ordering": ["-report_date", "product__name"],
                "unique_together": {("product", "report_date", "period")},
            },
        ),
        migrations.CreateModel(
            name="PurchaseReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Report Date"
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="Period",
                    ),
                ),
                (
                    "total_orders",
                    models.PositiveIntegerField(default=0, verbose_name="Total Orders"),
                ),
                (
                    "total_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Total Order Value",
                    ),
                ),
                (
                    "average_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Average Order Value",
                    ),
                ),
                (
                    "total_suppliers",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Suppliers"
                    ),
                ),
                (
                    "active_suppliers",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Active Suppliers"
                    ),
                ),
                (
                    "total_products_purchased",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Products Purchased"
                    ),
                ),
                (
                    "on_time_delivery_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="On-Time Delivery Rate (%)",
                    ),
                ),
                (
                    "order_accuracy_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Order Accuracy Rate (%)",
                    ),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Total Spent",
                    ),
                ),
                (
                    "average_cost_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Average Cost per Unit",
                    ),
                ),
                (
                    "top_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="top_purchase_reports",
                        to="inventory.product",
                        verbose_name="Top Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Report",
                "verbose_name_plural": "Purchase Reports",
                "ordering": ["-report_date"],
                "unique_together": {("report_date", "period")},
            },
        ),
        migrations.CreateModel(
            name="SalesVsPurchaseAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Report Date"
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="Period",
                    ),
                ),
                (
                    "total_sales",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Total Sales",
                    ),
                ),
                (
                    "sales_orders_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Sales Orders Count"
                    ),
                ),
                (
                    "average_sale_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Average Sale Price",
                    ),
                ),
                (
                    "total_purchases",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Total Purchases",
                    ),
                ),
                (
                    "purchase_orders_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Purchase Orders Count"
                    ),
                ),
                (
                    "average_purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Average Purchase Price",
                    ),
                ),
                (
                    "gross_margin",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Gross Margin",
                    ),
                ),
                (
                    "gross_margin_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Gross Margin (%)",
                    ),
                ),
                (
                    "top_purchased_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="top_purchase_reports_analysis",
                        to="inventory.product",
                        verbose_name="Top Purchased Product",
                    ),
                ),
                (
                    "top_selling_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="top_sales_reports",
                        to="inventory.product",
                        verbose_name="Top Selling Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales vs Purchase Analysis",
                "verbose_name_plural": "Sales vs Purchase Analyses",
                "ordering": ["-report_date"],
                "unique_together": {("report_date", "period")},
            },
        ),
        migrations.CreateModel(
            name="SupplierPerformanceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Report Date"
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="Period",
                    ),
                ),
                (
                    "total_orders",
                    models.PositiveIntegerField(default=0, verbose_name="Total Orders"),
                ),
                (
                    "completed_orders",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Completed Orders"
                    ),
                ),
                (
                    "cancelled_orders",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Cancelled Orders"
                    ),
                ),
                (
                    "on_time_deliveries",
                    models.PositiveIntegerField(
                        default=0, verbose_name="On-Time Deliveries"
                    ),
                ),
                (
                    "late_deliveries",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Late Deliveries"
                    ),
                ),
                (
                    "average_delivery_days",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=5,
                        verbose_name="Average Delivery Days",
                    ),
                ),
                (
                    "quality_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        verbose_name="Quality Rating",
                    ),
                ),
                (
                    "return_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Return Rate (%)",
                    ),
                ),
                (
                    "total_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Total Order Value",
                    ),
                ),
                (
                    "average_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Average Order Value",
                    ),
                ),
                (
                    "payment_terms_compliance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Payment Terms Compliance (%)",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_reports",
                        to="inventory.supplier",
                        verbose_name="Supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Performance Report",
                "verbose_name_plural": "Supplier Performance Reports",
                "ordering": ["-report_date", "supplier__name"],
                "unique_together": {("supplier", "report_date", "period")},
            },
        ),
    ]
